-- Migration 0040 — UNIQUE idempotency_key on critical write tables.
--
-- Wave 1 §3. Every business-critical write must carry a deterministic
-- idempotency key generated by `omerion_core.util.idempotency`. A
-- duplicate insert with the same key is a silent no-op at the DB layer.
--
-- Tables touched:
--   * agent_runs           — wrapper-managed runs
--   * business_outcomes    — revenue ledger (Wave 2.3 also enforces source)
--   * opportunities        — deal pipeline (Wave 2.1 also enforces value bounds)
--   * blueprints           — discovery-call blueprints
--
-- Already constrained (no change needed):
--   * outbound_communications.idempotency_key UUID NOT NULL UNIQUE
--     (migration 0004_operational_tables.sql:24)
--
-- Strategy:
--   * Add the column as NULLABLE TEXT so the migration is non-blocking.
--   * Use a PARTIAL UNIQUE INDEX that excludes NULL rows. Existing rows
--     keep NULL (no backfill required); all new rows written by the
--     wrapper carry a key and are deduped.
--   * 64-char SHA-256 hex keys fit comfortably in TEXT.
--
-- Safe to re-run (idempotent guards on every statement).

BEGIN;

-- ─── agent_runs ────────────────────────────────────────────────────────
ALTER TABLE agent_runs
    ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS agent_runs_idempotency_uidx
    ON agent_runs (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMENT ON COLUMN agent_runs.idempotency_key IS
    'Wrapper-generated SHA-256 dedupe key. NULL on legacy rows; required on new rows written by agent_wrapper.run().';

-- ─── business_outcomes ─────────────────────────────────────────────────
ALTER TABLE business_outcomes
    ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS business_outcomes_idempotency_uidx
    ON business_outcomes (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMENT ON COLUMN business_outcomes.idempotency_key IS
    'Wave 1: dedupe key. Paired with Wave 2.3 source-of-truth gate (no agent_inference values).';

-- Also enforce (run_id, outcome_type) uniqueness so the same run cannot
-- record the same outcome twice (Wave 2 §3 requirement).
CREATE UNIQUE INDEX IF NOT EXISTS business_outcomes_run_outcome_uidx
    ON business_outcomes (run_id, outcome_type)
    WHERE run_id IS NOT NULL;

-- ─── opportunities ─────────────────────────────────────────────────────
ALTER TABLE opportunities
    ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS opportunities_idempotency_uidx
    ON opportunities (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMENT ON COLUMN opportunities.idempotency_key IS
    'Wave 1: dedupe key. value_est_usd is a bucket midpoint (Wave 2.2), never a raw LLM number.';

-- ─── blueprints ────────────────────────────────────────────────────────
ALTER TABLE blueprints
    ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS blueprints_idempotency_uidx
    ON blueprints (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMENT ON COLUMN blueprints.idempotency_key IS
    'Wave 1: dedupe key. hitl_flags Pydantic-validated before insert (Wave 2.4).';

-- ─── revenue_events sanity (Wave 0 stripe migration prerequisite) ──────
-- The Stripe webhook handler relies on UNIQUE(stripe_event_id) for replay
-- safety. Add it if missing.
ALTER TABLE revenue_events
    ADD COLUMN IF NOT EXISTS stripe_event_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS revenue_events_stripe_event_uidx
    ON revenue_events (stripe_event_id)
    WHERE stripe_event_id IS NOT NULL;

COMMENT ON COLUMN revenue_events.stripe_event_id IS
    'Stripe event.id — UNIQUE so replays are silent no-ops (omerion_core/inbound/stripe.py).';

COMMIT;
